[package]
name = "simcity_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_egui = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
simcity_core = { path = "../simcity_core" }
simcity_data = { path = "../simcity_data" }
simcity_debug = { path = "../simcity_debug" }
simcity_sim = { path = "../simcity_sim" }
