/** All time here is game time; the UI alone converts elapsed real time. */
export const LIFE_RULES = {
  secondsPerMinute: 60,
  secondsPerDay: 86_400,
  startingMinute: 360,
  familyCount: 250,
  investorCount: 200,
  familyCapital: 80_000,
  investorCapital: 100_000,
  familyIntervalSeconds: 600,
  industrialEmploymentShare: 0.7,
  familiesPerStore: 8,
  externalGoods: 50_000,
  workerAge: 18,
  retirementAge: 65,
  wagePeriodSeconds: 900,
  wagePerPeriod: 3,
  productionWorkerSeconds: 5_760,
  productionUnitCost: 2,
  importPrice: 20,
  wholesalePrice: 30,
  warehousePrice: 35,
  retailPrice: 70,
  deliveryFee: 12,
  deliverySize: 16,
  maxTrucks: 24,
  loadingSeconds: 30,
  unloadingSeconds: 30,
  taxRate: 0.1,
  roadUpkeepPerKm: 100,
  warehouseUpkeep: 80,
  workStartMinute: 540,
  workEndMinute: 1020,
  walkMetersPerMinute: 72,
  carMetersPerMinute: 330,
  maximumCommuteMinutes: 120,
} as const;
export const BUILDING_RULES = {
  residential: {
    cost: 32_000,
    durationSeconds: 1800,
    capacity: 16,
    jobs: 0,
    qualification: 0,
    parking: 4,
    inventoryCapacity: 0,
    workingCapital: 0,
  },
  commercial: {
    cost: 16_000,
    durationSeconds: 1800,
    capacity: 0,
    jobs: 6,
    qualification: 0,
    parking: 2,
    inventoryCapacity: 64,
    workingCapital: 20_000,
  },
  industrial: {
    cost: 25_000,
    durationSeconds: 2700,
    capacity: 0,
    jobs: 8,
    qualification: 0,
    parking: 2,
    inventoryCapacity: 96,
    workingCapital: 20_000,
  },
  warehouse: {
    cost: 0,
    durationSeconds: 2400,
    capacity: 0,
    jobs: 0,
    qualification: 0,
    parking: 2,
    inventoryCapacity: 192,
    workingCapital: 0,
  },
} as const;
